apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus-example-app
  name: prometheus-example-app-monitor
  namespace: openshift-monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 20s
    port: 8080-tcp
    path: /metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - hyperion
  selector:
    matchLabels:
      app: prometheus-example-app