# now this monitor is not working since router basic auth config cannot passed to prometheus
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: router
  name: router-monitor
  namespace: openshift-monitoring
spec:
  endpoints:
  - interval: 20s
    port: 1936-tcp
    path: /metrics
    scheme: http
    basicAuth:
      password:
        name: router-basic-auth
        key: password
      username:
        name: router-basic-auth
        key: user
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      router: router