apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
spec:
  clusterIP: None
  ports:
  - name: client
    port: 6379
    protocol: TCP
    targetPort: 6379
  - name: gossip
    port: 16379
    protocol: TCP
    targetPort: 16379
  selector:
    app: redis-cluster
  sessionAffinity: None
  type: ClusterIP